1. What does Pandas stand for?<br>
> Panel Data
2. What are the 2 collections used in Pandas?<br>
> Series, DataFrame
3. Name 4 things Pandas can do for us.<br>
> Data cleansing, Merges and joins, Loading and saving data, Data inspection
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?<br>
> It must be assigned to a new variable (new = df.sort())
5. What is a CSV
> Comma separated files, that contains plain text
6. When cleaning data what values do we not like in our data?
> Missing Values

In [ ]:
#7.Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). 
import numpy as np
Array1 = np.ones((2,3,2))
Array1
#You can use the reshape method -- `.reshape()`
newshape1 = np.reshape(Array1, (3,2,2))
print("New Shape...", newshape1)

In [ ]:
#8.Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
import numpy as np

array2 = np.linspace(0,20,6)
print(array2)

#9. Make a Deep Copy of the above array
copied_list = array2.copy()
print("The Copy....", copied_list)


In [131]:
#11.Concatenate these 3 arrays into a new array named 'newArray'
import numpy as np

arraya = np.array([[25, 16]])
arrayb = np.array([[11, 2], [13, 4]])
arrayc = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arraya,arrayb,arrayc))
print(newArray)

#12. Sort 'newArray' in order into 'sortedArray'
sortedarray = np.sort(newArray)
print("sorted...", sortedarray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
sorted... [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [143]:
#13.Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
import numpy as np

newshape3 = np.reshape(sortedarray, (2,-3))
print(newshape3)

#14.Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
#newshape3
#a,b,c,d = newshape3
#got an error that says not enough values to unpack



[[16 25  2 11  4 13]
 [ 7 81  5  6 11 12]]


In [ ]:
#15.Combined and sort the following arrays into one called 'comboArray' ...
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboarray = np.concatenate((one, two, three))
comboarraysorted = np.sort(comboarray)
print("final...", comboarraysorted)

#16.Take 'comboArray' and perform the following slicing activities:
print("2nd element...", comboarraysorted[1])
print("3rd element to the last", comboarraysorted[2:24])
print("4th to the 14th elements", comboarraysorted[4:15])
print("last 6 elements", comboarraysorted[-6:])
print("from #0 up to and including #15", comboarraysorted[0:-10])
print("from #20 every even element to the end...", comboarraysorted[[-8,-6,-4,-2]])
print("from the last element moving forward every 5th element...", comboarraysorted[[-1,-6,-11,-16,-21]])

In [ ]:
#20.Using `Series`, create a `DataFrame` that looks like this:
import pandas as pd

ingredients = pd.Series(["flour","milk","eggs","spam"], name='Ingredients')
quantity = pd.Series([4,1,2,1], name='quantity')
unit = pd.Series(["cups","cup","large","can"], name='Unit')

dinner = pd.concat([ingredients,quantity,unit], axis=1)
dinner

#Ingredients | Quantity | Unit |
#Flour | 4 | cups |
#Milk | 1 | cup |
#Eggs | 2 | large |
#Spam | 1 | can |
# Name: Dinner, dtype: object

In [ ]:
#21.Take this data and create a DataFrame named studentData
import pandas as pd

Name = pd.Series(["Jai","Janusha","Gaurav","Anuj"], name="Name")
Height = pd.Series([5.1,6.2,5.1,5.2], name='Height')
Qualification = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name='Qualification')
address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakhar'], name='Address')
Age = pd.Series([21, 23, 24, 21], name='Age')
Pets = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name='Pets')
sport = pd.Series(['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'], name='Sports')

studentdata = pd.concat([Name,Height,Qualification,address,Age,Pets,sport], axis=1)
#print(studentdata)

#22.Add a new column to the DataFrame with the following deserts:
studentdata =studentdata.assign(Desserts =["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"])
#studentdata

#23. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentdata.sort_values(by = ['Name','Address'], 
                        ascending = [True, True], inplace= True)
print(studentdata)


In [114]:
#24. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:
import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('Cows_and_Goats.csv')

#25.(A) Using Pandas, make your own .CSV file with data on vegetables and save it.
Veggies = pd.DataFrame([["green","prepper"],["Red","tomatoe"],["white","onion"]],
                        columns= ["Color","Vegetables"])
#Veggies 
Veggies.to_csv('Veggie_tales.csv')
#(B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
Veggies2 = Veggies.assign(Farm =["Sonnys","Beans","hugo"])
#Veggies2
Veggies2.to_csv('talesofveggie.csv')